-- Cloud saves for the coach profile.
-- Only the coach's name, avatar and match statistics are stored; emails stay in Supabase Auth.
-- Every row belongs to one account and row level security lets a player see and write only their own rows.

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '' check (char_length(name) <= 20),
  avatar text,
  rating integer not null default 0 check (rating >= 0),
  -- The whole profile snapshot as the game saves it (versioned JSON).
  data jsonb not null check (pg_column_size(data) <= 65536),
  -- Bumped by one on every save, so two devices cannot overwrite each other unnoticed.
  revision integer not null default 1 check (revision >= 1),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'Coach profile snapshot, one row per account.';

create table public.matches (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- Generated by the game; only unique per player, so nobody can squat another player's ids.
  id text not null check (char_length(id) <= 64),
  played_at timestamptz not null,
  verdict text not null check (verdict in ('win', 'loss', 'draw')),
  data jsonb not null check (pg_column_size(data) <= 16384),
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);

comment on table public.matches is 'Every finished match, kept for history and a future server-checked leaderboard.';

create index matches_by_player on public.matches (user_id, played_at desc);

-- Saves must go revision N -> N + 1, which is what the game's optimistic locking relies on.
create function public.profiles_before_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.id <> old.id then
    raise exception 'profile id cannot change';
  end if;

  if new.revision <> old.revision + 1 then
    raise exception 'profile revision must go from % to %', old.revision, old.revision + 1;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_before_update
before update on public.profiles
for each row execute function public.profiles_before_update();

alter table public.profiles enable row level security;
alter table public.matches enable row level security;

-- Guest (anonymous) players sign in too and get the authenticated role; signed-out visitors get nothing.
revoke all on table public.profiles, public.matches from anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert on table public.matches to authenticated;

create policy "Players read their own profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy "Players create their own profile"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

create policy "Players update their own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Players read their own matches"
on public.matches for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Players add their own matches"
on public.matches for insert to authenticated
with check ((select auth.uid()) = user_id);
